version: '3.7'
networks: 
  backend:
    driver: bridge

services: 
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: full_backend
    restart: always
    volumes: 
      - ./backend:/var/www/backend
    networks: 
      - backend
  
  frontend:
    build: 
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: full_frontend
    restart: always
    volumes: 
      - ./frontend:/var/www/frontend
    networks: 
      - backend

  nginx:
    container_name: full_nginx
    image: nginx:1.16.1-alpine
    restart: always
    volumes: 
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./docker/log/nginx:/var/log/nginx
    ports: 
      - '80:80'
      - '443:443'
    networks: 
    - backend

  mysql:
    container_name: full_mysql
    image: mysql:5.7.22
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=abcdef123
      - MYSQL_DATABASE=backend
      - MYSQL_USER=dudy206
      - MYSQL_PASSWORD=abcdef123
    networks: 
      - backend
    
  phpmyadmin:
    container_name: full_phpmyadmin
    image: phpmyadmin:5.1.0
    environment: 
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=abcdef123
      - UPLOAD_LIMIT=20000000
    ports: 
      - '8181:80'
    networks: 
      - backend
    depends_on: 
      - mysql
